version: '2'
services:
  db:
    image: "postgres:9.6.5"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - env_file
    networks:
      - db_nw
  flaskapp:
    build: ./server/
    working_dir: /opt/services/flaskapp/src/server
    env_file:
      - env_file
    volumes:
      - .:/opt/services/flaskapp/src
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db
  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./client/app:/usr/share/nginx/html
    networks:
      - web_nw
    depends_on:
      - flaskapp
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
  dbdata: